# Generated by Django 4.2.6 on 2023-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('address_details', models.JSONField(null=True)),
                ('work_experience', models.JSONField(null=True)),
                ('qualifications', models.JSONField(null=True)),
                ('projects', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
